---
- name: Generate config files-ansible roles style
  template:
    src: access_switch.j2
    dest: /home/mbiro/pynet/class5/generated_files/exercise2/{{ item.hostname }}.txt
  with_items: "{{switches}}"
...
