---
- hosts: localhost
  tasks:
    - name: Generate switch config file
      template:
        src: /home/mbiro/pynet/class5/template_files/access_switch.j2
        dest: /home/mbiro/pynet/class5/generated_files/exercise1/{{ item.hostname }}.txt
      with_items:
        - { hostname: 'Switch1',
          secret: 'cisco',
          access_vlan: '10',
          ip_addr: '1.1.1.10',
          default_gateway: '1.1.1.1',
          snmp_community: 'readSNMP',
          }
        - { hostname: 'Switch2',
          secret: 'cisco',
          access_vlan: '20',
          ip_addr: '1.1.2.10',
          default_gateway: '1.1.2.1',
          snmp_community: 'readSNMP',
          }
        - { hostname: 'Switch3',
          secret: 'cisco',
          access_vlan: '10',
          ip_addr: '1.1.3.10',
          default_gateway: '1.1.3.1',
          snmp_community: 'readSNMP',
          }
        - { hostname: 'Switch4',
          secret: 'cisco',
          access_vlan: '10',
          ip_addr: '1.1.4.10',
          default_gateway: '1.1.4.1',
          snmp_community: 'readSNMP',
          }
        - { hostname: 'Switch5',
          secret: 'cisco',
          access_vlan: '10',
          ip_addr: '1.1.5.10',
          default_gateway: '1.1.5.1',
          snmp_community: 'readSNMP',
          }
...
